Parameters:
  Name:
    Type: String
  Password:
    Type: String
  ShortName:
    Type: String
  VPC:
    Type: AWS::EC2::VPC::Id
  SubnetIDs:
    Type: List<AWS::EC2::Subnet::Id>
Resources:
  AD:
    Type: AWS::DirectoryService::MicrosoftAD
    Properties:
      Name: !Ref Name
      Password: !Ref Password
      ShortName: !Ref ShortName
      VpcSettings:
        SubnetIds: !Ref SubnetIDs
        VpcId: !Ref VPC